### ISSUE TITLE
Installation / setup instructions

### ISSUE THREAD

**Issue by 2073036n** [craigmccallum/weather_station#15]
It would be really helpful to have a section explaining how to install / setup the software development environment you're using e.g. languages / libraries / frameworks you've installed and the versions you are using.

Team 11

**Comment by TheAliRobertson** [comment]
Really interesting concept and idea! It would be really good if you could have a block diagram showing an outline of the process and structure of your project. This would help in understanding the overall systems operation as well as each individual components role.

**Comment by damir2020** [comment]
Thank you for your interest in our project. You can find installation instructions here:  
https://github.com/craigmccallum/weather_station/blob/damir2020-patch-1/03_web_app/readme.pdf
