### ISSUE TITLE
A Few Software Improvements

### ISSUE THREAD

**Issue by 2077762b** [craigmccallum/weather_station#17]
This repository generally looks very good. The hardware wiki page is very informative. Just a few suggestions for the software: 
* It is generally good practice to use the .gitignore file to stop compiled files from entering the repository.
* You mention installation in the README file but there appears to not actually be any instructions on how to do this.
* The class names aren't particularly meaningful.
* While there is some inline commentary in the code, it would be much easier to understand if each function in the class definitions had a comment at the top explaining its function

**Team 10**

**Comment by damir2020** [comment]
Comments to the code added
