### ISSUE TITLE
About PCB

### ISSUE THREAD

**Issue by Cao-Jinyu** [craigmccallum/weather_station#21]
Where you find the padstack for the Raspberry Pi GPIO?

**Comment by acra6488** [comment]
Hi Cao-Jinyu and thank you for your comment.
The padstack can be found with a quick google search and by going onto a trustworthy website such as modmypi.com
Here is a link (see bottom of comment) to a compatible connector for the Raspbery PI which gives dimensions of
52.0 mm x 5 mm x 11.7 mm (L x W x H) 
and a pitch (distance between pins) of 2.54 mm
Then a quick look at the specification sheet tells us the pin diameter is of 0.6 mm.
Hope this helps!
https://www.modmypi.com/raspberry-pi/gpio-and-breadboarding/40-pin-gpio-connectors/40-pin-gpio-connector-header-extender
