### ISSUE TITLE
maybe you took too many bits here!

### ISSUE THREAD

**Issue by Ranuncolo** [craigmccallum/weather_station#26]
https://github.com/craigmccallum/weather_station/blob/af47479d806b8b93cf9879434e7932455694e8df/02_data_acquisition_and_processing/work.cpp#L55

Hello,

Sorry for bothering you but we are using the same humidity sensor and I was watching how you converted from digital to the proper humidity value. I've seen you convert the whole two bytes but if you check on page 6 of the data sheet it says that the value requires only 14 bits! If you try with the 16 bits binary number you may have a humidity value greater than 100%.

Sorry again and see you later!

Kind regards,

René

**Comment by damir2020** [comment]
Thank you  for your interest in our project. We fixed this issue. You can find solution in our new branch https://github.com/craigmccallum/weather_station/tree/damir2020-patch-1
