### ISSUE TITLE
Binary files

### ISSUE THREAD

**Issue by berndporr** [craigmccallum/weather_station#28]
Hi,
can you remove the binary files and if you use C++ the ending is .cpp and not .c. Can you fix it:
https://github.com/craigmccallum/weather_station/tree/master/02_data_acquisition_and_processing

**Comment by damir2020** [comment]
Thank you for your comments. The issue has been fixed. The binary files have been removed.  The ending of the c++ code file has been corrected to  .cpp. All necessary changes has been done in Makefile as well.
